package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// ProfileSpec is everything needed to materialise a Codex home and invoke the
// CLI. It is deliberately decoupled from the database model so this package can
// be tested without storage.
type ProfileSpec struct {
	Name            string
	Model           string
	ReasoningEffort string
	SandboxMode     string
	ApprovalPolicy  string
	ExtraConfig     string
	WorkDir         string
	IsMinimal       bool
}

// SandboxOrDefault returns the sandbox mode, defaulting to read-only.
func (s ProfileSpec) SandboxOrDefault() string {
	if s.SandboxMode == "" {
		return "read-only"
	}
	return s.SandboxMode
}

// EffortOrDefault returns the reasoning effort. none/minimal/empty become low:
// those values are not offered, and gpt-5.6-luna rejects them.
func (s ProfileSpec) EffortOrDefault() string {
	switch s.ReasoningEffort {
	case "low", "medium", "high", "xhigh", "max":
		return s.ReasoningEffort
	default:
		return "low"
	}
}

// ApprovalOrDefault returns the approval policy, defaulting to never so an
// unattended run cannot block on a prompt.
func (s ProfileSpec) ApprovalOrDefault() string {
	switch s.ApprovalPolicy {
	case "never", "on-request", "on-failure", "untrusted":
		return s.ApprovalPolicy
	default:
		return "never"
	}
}

// minimalFeatureDisables are the heavy Codex capabilities switched off in
// minimal mode. They contribute large tool definitions to every request and are
// not useful for plain chat. Note that code_mode_host is deliberately NOT
// disabled: Codex fails closed when it is off, which breaks the turn.
var minimalFeatureDisables = []string{
	"apps",
	"browser_use",
	"browser_use_external",
	"browser_use_full_cdp_access",
	"computer_use",
	"auth_elicitation",
	"compaction_image_budget",
	"content_item_kinds",
	"enable_request_compression",
}

// GenerateConfig renders the config.toml written into a profile's CODEX_HOME.
// Because Codex reads the whole file from a directory we own, the generated
// config contains no MCP servers, no skills and no project entries, which is
// what makes a profile genuinely isolated from the operator's ~/.codex.
func GenerateConfig(spec ProfileSpec) string {
	var b strings.Builder

	b.WriteString("# Generated by cronCodex for profile ")
	b.WriteString(tomlString(spec.Name))
	b.WriteString(". Manual edits are overwritten on save.\n\n")

	if spec.Model != "" {
		b.WriteString("model = " + tomlString(spec.Model) + "\n")
	}
	b.WriteString("model_reasoning_effort = " + tomlString(spec.EffortOrDefault()) + "\n")
	b.WriteString("approval_policy = " + tomlString(spec.ApprovalOrDefault()) + "\n")
	// sandbox_mode is written to the config as well as passed on the command
	// line, because `codex exec resume` accepts no -s flag and would otherwise
	// fall back to a default sandbox for every follow-up turn.
	b.WriteString("sandbox_mode = " + tomlString(spec.SandboxOrDefault()) + "\n")

	if spec.IsMinimal {
		b.WriteString("\n# Minimal mode: reduce per-request context to the essentials.\n")
		b.WriteString("[features]\n")
		for _, f := range minimalFeatureDisables {
			b.WriteString(f + " = false\n")
		}
	}

	if extra := strings.TrimSpace(spec.ExtraConfig); extra != "" {
		b.WriteString("\n# Operator-supplied overrides.\n")
		b.WriteString(extra)
		b.WriteString("\n")
	}
	return b.String()
}

// tomlString quotes a Go string as a TOML basic string. strconv.Quote already
// emits the same escaping rules TOML expects for the characters we can receive.
func tomlString(s string) string { return strconv.Quote(s) }

// HomeDir is the CODEX_HOME directory for a profile.
func (s *Service) HomeDir(name string) string {
	return filepath.Join(s.homeRoot, name)
}

// WorkspaceDir is the scratch working directory for a profile. Keeping Codex
// in an empty directory prevents it from picking up a project's AGENTS.md and
// other repository context.
func (s *Service) WorkspaceDir(spec ProfileSpec) string {
	if wd := strings.TrimSpace(spec.WorkDir); wd != "" {
		return wd
	}
	return filepath.Join(s.workspaceRoot, spec.Name)
}

// EnsureHome creates the profile's CODEX_HOME, links in the Codex credentials
// and writes the generated config. It returns the home directory.
func (s *Service) EnsureHome(spec ProfileSpec) (string, error) {
	if err := validateHomeName(spec.Name); err != nil {
		return "", err
	}
	home := s.HomeDir(spec.Name)
	if err := os.MkdirAll(home, 0o755); err != nil {
		return "", fmt.Errorf("create codex home: %w", err)
	}
	if err := s.linkAuth(home); err != nil {
		return "", err
	}
	cfgPath := filepath.Join(home, "config.toml")
	if err := os.WriteFile(cfgPath, []byte(GenerateConfig(spec)), 0o644); err != nil {
		return "", fmt.Errorf("write config.toml: %w", err)
	}
	if err := os.MkdirAll(s.WorkspaceDir(spec), 0o755); err != nil {
		return "", fmt.Errorf("create workspace: %w", err)
	}
	return home, nil
}

// linkAuth symlinks the operator's Codex credentials into the profile home.
// A symlink is used rather than a copy so the credential is never duplicated,
// and so a token refresh by Codex is visible to every profile. A missing
// source is not fatal: Codex may be configured through other means.
func (s *Service) linkAuth(home string) error {
	if s.authSource == "" {
		return nil
	}
	info, err := os.Stat(s.authSource)
	if err != nil || info.IsDir() {
		s.log.Warn("codex credentials not found; profile will rely on ambient authentication",
			"auth_source", s.authSource)
		return nil
	}

	dst := filepath.Join(home, "auth.json")
	// Remove a stale link or copy so the target can be refreshed.
	if _, err := os.Lstat(dst); err == nil {
		if err := os.Remove(dst); err != nil {
			return fmt.Errorf("replace auth.json: %w", err)
		}
	}
	if err := os.Symlink(s.authSource, dst); err != nil {
		return fmt.Errorf("link auth.json: %w", err)
	}
	return nil
}

// RemoveHome deletes a profile's CODEX_HOME and scratch workspace.
func (s *Service) RemoveHome(name string) error {
	if err := validateHomeName(name); err != nil {
		return err
	}
	var firstErr error
	for _, dir := range []string{s.HomeDir(name), filepath.Join(s.workspaceRoot, name)} {
		if err := os.RemoveAll(dir); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

// validateHomeName guards against a profile name escaping the home root. The
// store enforces the same rule, so this is defence in depth for a value that
// becomes a filesystem path.
func validateHomeName(name string) error {
	if name == "" {
		return fmt.Errorf("profile name is required")
	}
	if name == "." || name == ".." || strings.ContainsAny(name, `/\`) {
		return fmt.Errorf("invalid profile name %q", name)
	}
	return nil
}

// PreviewConfig renders the config a profile would receive, for display in the
// web UI.
func (s *Service) PreviewConfig(spec ProfileSpec) string { return GenerateConfig(spec) }
